num_class: 5
num_heading_bin: 12
num_size_cluster: 5
type2class:
  Benchy: 0
  CoffeeMug: 1
  F1Car: 2
  RubberDuck: 3
  Shuttle: 4
type_mean_size:
  Benchy:
  - 1.78
  - 1.44
  - 0.92
  CoffeeMug:
  - 1.5
  - 1.5
  - 1.4
  F1Car:
  - 2.95
  - 1.29
  - 0.81
  RubberDuck:
  - 1.39
  - 1.3
  - 1.21
  Shuttle:
  - 1.72
  - 1.44
  - 0.72
